CREATE TYPE star_rating AS ENUM('1', '2', '3', '4', '5');

CREATE TABLE bookmarks(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title varchar(50) NOT NULL,
  url text NOT NULL,
  rating star_rating NOT NULL,
  description text NOT NULL
);
